name: proyecto2eva_budget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  sqflite: ^2.4.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4+4
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  http: any
  #Firebase dependencies
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2 #autotenticación de usuarios
  cloud_firestore: ^5.6.6 
  flutter_secure_storage: ^9.2.4
  logger: any #mensaje en consola
  translator: ^1.0.3+1 #igual hay que quitarlo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  #añadir esto
  generate: true
  assets:
    - assets/currencies.json